[package]
name = "cggmp21"
version = "0.1.0"
edition = "2021"

[dependencies]
k256 = { version = "0.11", default-features = false, features = ["ecdsa", "arithmetic", "hash2curve"] }
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
sha2 = { version = "0.10", default-features = false }
sha3 = { version = "0.10", default-features = false }
digest = { version = "0.10", default-features = false, features = ["alloc"]}

crypto-bigint = "0.5.0-pre.2"
crypto-primes = { git = "https://github.com/entropyxyz/crypto-primes.git", branch = "master" }

[dev-dependencies]
num-modular = { version = "0.5", features = ["num-bigint"] }
num-bigint = "0.4"
num-integer = "0.1"
