[package]
name = "cggmp21"
version = "0.1.0"
edition = "2021"

[dependencies]
k256 = { version = "0.11", default-features = false, features = ["ecdsa", "arithmetic", "hash2curve"] }
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
sha2 = { version = "0.10", default-features = false }
sha3 = { version = "0.10", default-features = false }
digest = { version = "0.10", default-features = false, features = ["alloc"]}

crypto-bigint = { version = "0.5", features = ["serde"] }
crypto-primes = "0.2"

serde = { version = "1", features = ["derive"] }
rmp-serde = "1"

[dev-dependencies]
num-modular = { version = "0.5", features = ["num-bigint"] }
num-bigint = "0.4"
num-integer = "0.1"
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
rand = "0.8"
