[package]
name = "synedrion"
version = "0.0.9"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "Threshold signing library based on Canetti-Gennaro-Goldfeder-Makriyannis-Peled '21 scheme"
repository = "https://github.com/entropyxyz/synedrion"
readme = "README.md"
categories = ["cryptography", "no-std"]

[dependencies]
signature = { version = "2", default-features = false, features = ["alloc"] }
# TODO: we only need `serde` feature in tests
k256 = { version = "0.13", default-features = false, features = ["ecdsa", "arithmetic", "serde"] }
rand_core = { version = "0.6.4", default-features = false, features = ["getrandom"] }
sha2 = { version = "0.10", default-features = false }
sha3 = { version = "0.10", default-features = false }
digest = { version = "0.10", default-features = false, features = ["alloc"]}
hex = { version = "0.4", default-features = false, features = ["alloc"] }
base64 = { version = "0.21", default-features = false, features = ["alloc"] }
rand_chacha = { version = "0.3", default-features = false }

crypto-bigint = { version = "0.5", features = ["serde"] }
crypto-primes = "0.5"

serde = { version = "1", features = ["derive"] }
rmp-serde = "1"

[dev-dependencies]
num-modular = { version = "0.5", features = ["num-bigint"] }
num-bigint = "0.4"
num-integer = "0.1"
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
rand = "0.8"
